name: Smart Address
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Smart Address
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0196d9'
    - '#ff0000'
    - '#0000ff'
    - '#a4354d'
    - '#00ffff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9415458883158863
  rhythmicContrast: 1
purpose: []
