name: Viplav
favicon: null
layout_spectrum: 0.7788592111319304
typography_spectrum: 0.07762509002350271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5941024161875248
  lightness: 0.028338755248114467
  saturation: 0.9415458883158863
  rhythmicContrast: 0.8337231911718845
purpose: []
